[deps]
Colors = "0.12.3"
CSV = "0.7.4"
DelimitedFiles = "1.4.2"
GR = "0.51.0"
IJulia = "1.21.2"
ImageView = "0.10.9"
ImageInTerminal = "0.4.4"
FileIO = "1.4.0"
ImageFiltering = "0.6.14"
Images = "0.22.4"
ImageFeatures = "0.4.2"
LinearAlgebra = "0.2.3"
Plots = "1.5.5"
PyPlot = "2.9.0"
Random = "1.4.0"
GtkReactive = "1.0.3"
Roots = "1.0.0"
SymEngine = "0.8.2"
Statistics = "1.4.0"
TestImages = "0.6.3"

[compat]
julia = "1.4.2"
