[deps]
Colors = "^0.12"
CSV = "^0.7"
DelimitedFiles = "^1.4"
GR = "^0.51"
IJulia = "^1.21"
ImageView = "^0.10"
ImageInTerminal = "^0.4"
FileIO = "^1.4"
ImageFiltering = "^0.6"
Images = "^0.22"
ImageFeatures = "^0.4"
LinearAlgebra = "^0.2"
Plots = "^1.5"
PyPlot = "^2.9"
Random = "^1.4"
GtkReactive = "^1.0"
Roots = "^1.0"
SymEngine = "^0.8"
Statistics = "^1.4"
TestImages = "^0.6"

[compat]
julia = "1.4"
